import { Hono } from "hono";
import type { AppEnv } from "../../lib/auth.js";
import { adminAgentRoutes } from "./admin-agents.js";
import { adminAuthSettingsRoutes } from "./admin-auth-settings.js";
import { adminBackupSettingsRoutes } from "./admin-backup-settings.js";
import { adminDriveSettingsRoutes } from "./admin-drive-settings.js";
import { adminDriveSyncRoutes } from "./admin-drive-sync.js";
import { adminEmailSettingsRoutes } from "./admin-email-settings.js";
import { adminGcpCredentialsRoutes } from "./admin-gcp-credentials.js";
import { adminGroupRoutes } from "./admin-groups.js";
import { adminInvitationRoutes } from "./admin-invitations.js";
import { adminLlmConfigSetRoutes } from "./admin-llm-config-sets.js";
import { adminLlmSettingsRoutes } from "./admin-llm-settings.js";
import { adminReindexRoutes } from "./admin-reindex.js";
import { adminSiteSettingsRoutes } from "./admin-site-settings.js";
import { adminSpacePermissionRoutes } from "./admin-space-permissions.js";
import { adminStorageSettingsRoutes } from "./admin-storage-settings.js";
import { adminSystemUpdateRoutes } from "./admin-system-update.js";
import { adminUserRoutes } from "./admin-users.js";

export const adminRoutes = new Hono<AppEnv>();

adminRoutes.route("/", adminGroupRoutes);
adminRoutes.route("/", adminInvitationRoutes);
adminRoutes.route("/", adminUserRoutes);
adminRoutes.route("/", adminAgentRoutes);
adminRoutes.route("/", adminSpacePermissionRoutes);
adminRoutes.route("/", adminSiteSettingsRoutes);
adminRoutes.route("/", adminAuthSettingsRoutes);
adminRoutes.route("/", adminGcpCredentialsRoutes);
adminRoutes.route("/", adminEmailSettingsRoutes);
adminRoutes.route("/", adminLlmConfigSetRoutes);
adminRoutes.route("/", adminLlmSettingsRoutes);
adminRoutes.route("/", adminStorageSettingsRoutes);
adminRoutes.route("/", adminReindexRoutes);
adminRoutes.route("/", adminBackupSettingsRoutes);
adminRoutes.route("/", adminDriveSettingsRoutes);
adminRoutes.route("/", adminDriveSyncRoutes);
adminRoutes.route("/", adminSystemUpdateRoutes);
