"use client";

import { useCallback } from "react";
import type { ApiError } from "@/lib/api";
import type { SupportedLocale } from "@/lib/i18n";
import { defaultLocale, useLocale } from "@/lib/i18n";

type LocalizedMessages = Record<string, string>;
type ApiErrorLike = Pick<ApiError, "code" | "detail" | "message">;

const messagesByLocale: Record<SupportedLocale, LocalizedMessages> = {
  ja: {
    UNAUTHORIZED: "認証が必要です。",
    FORBIDDEN: "この操作を実行する権限がありません。",
    NOT_FOUND: "対象のリソースが見つかりません。",
    RATE_LIMITED: "試行回数が多すぎます。しばらく待ってから再試行してください。",
    REGISTER_REJECTED: "アカウント登録を開始できませんでした。",
    INVALID_TOKEN: "確認トークンが無効か期限切れです。",
    INVALID_CREDENTIALS: "メールアドレスまたはパスワードが正しくありません。",
    INVALID_REFRESH_TOKEN: "リフレッシュトークンが無効です。",
    GOOGLE_TOKEN_INVALID: "Google トークンが無効です。",
    INTERNAL_SERVER_ERROR: "サーバーエラーが発生しました。",
    UNKNOWN_ERROR: "不明なエラーが発生しました。",
    WIKI_PAGES_LIST_FAILED: "ページ一覧の読み込みに失敗しました。",
    WIKI_SEARCH_FAILED: "検索に失敗しました。",
    WIKI_PAGE_NOT_FOUND: "ページが見つかりません。",
    WIKI_PAGE_FORBIDDEN: "このページを表示する権限がありません。",
    WIKI_PAGE_FETCH_FAILED: "ページの読み込みに失敗しました。",
    WIKI_PAGE_CREATE_FAILED: "ページの作成に失敗しました。",
    WIKI_PAGE_PARENT_CYCLE: "親ページの設定で循環参照が発生します。",
    WIKI_PAGE_UPDATE_FAILED: "ページの更新に失敗しました。",
    WIKI_PAGE_DELETE_FAILED: "ページの削除に失敗しました。",
    WIKI_BLOCK_CREATE_FAILED: "ブロックの作成に失敗しました。",
    WIKI_BLOCK_NOT_FOUND: "ブロックが見つかりません。",
    WIKI_BLOCK_UPDATE_FAILED: "ブロックの更新に失敗しました。",
    WIKI_BLOCK_DELETE_FAILED: "ブロックの削除に失敗しました。",
    FILES_LIST_FAILED: "ファイル一覧の読み込みに失敗しました。",
    FILE_NOT_FOUND: "ファイルが見つかりません。",
    FILE_FETCH_FAILED: "ファイル情報の取得に失敗しました。",
    FILE_MULTIPART_REQUIRED: "multipart/form-data 形式で送信してください。",
    FILE_REQUIRED: "ファイルを指定してください。",
    FILE_UPLOAD_FAILED: "ファイルのアップロードに失敗しました。",
    FILE_PATH_INVALID: "ファイルパスが不正です。",
    FILE_DOWNLOAD_URL_FAILED: "ダウンロード URL の生成に失敗しました。",
    FILE_DELETE_FAILED: "ファイルの削除に失敗しました。",
    ADMIN_GROUPS_LIST_FAILED: "グループ一覧の読み込みに失敗しました。",
    ADMIN_AGENTS_LIST_FAILED: "AI エージェント一覧の読み込みに失敗しました。",
    ADMIN_AGENT_CREATE_FAILED: "AI エージェントの作成に失敗しました。",
    ADMIN_AGENT_NOT_FOUND: "AI エージェントが見つかりません。",
    ADMIN_AGENT_UPDATE_FAILED: "AI エージェントの更新に失敗しました。",
    ADMIN_GROUP_NAME_CONFLICT: "同じ名前のグループが既に存在します。",
    ADMIN_GROUP_CREATE_FAILED: "グループの作成に失敗しました。",
    ADMIN_GROUP_NOT_FOUND: "グループが見つかりません。",
    ADMIN_GROUP_FETCH_FAILED: "グループ情報の取得に失敗しました。",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "システムグループは変更できません。",
    ADMIN_GROUP_UPDATE_FAILED: "グループの更新に失敗しました。",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "システムグループは削除できません。",
    ADMIN_GROUP_DELETE_FAILED: "グループの削除に失敗しました。",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "グループメンバーの読み込みに失敗しました。",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "グループメンバーの追加に失敗しました。",
    ADMIN_MEMBERSHIP_NOT_FOUND: "メンバーシップが見つかりません。",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "メンバーシップの削除に失敗しました。",
    ADMIN_USERS_LIST_FAILED: "ユーザー一覧の読み込みに失敗しました。",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "ユーザーの所属更新に失敗しました。",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "ページ権限の読み込みに失敗しました。",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "ページ権限の更新に失敗しました。",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "ページ権限が見つかりません。",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "ページ権限の削除に失敗しました。",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "ページ継承設定の読み込みに失敗しました。",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "ページ継承設定の更新に失敗しました。",
    ADMIN_KPI_OVERVIEW_FAILED: "KPI の読み込みに失敗しました。",
    MEETINGS_LIST_FAILED: "会議一覧の読み込みに失敗しました。",
    MEETING_NOT_FOUND: "会議が見つかりません。",
    MEETING_FORBIDDEN: "この会議にアクセスする権限がありません。",
    MEETING_FETCH_FAILED: "会議情報の読み込みに失敗しました。",
    MEETING_CREATE_FAILED: "会議の作成に失敗しました。",
    MEETING_UPDATE_FAILED: "会議の更新に失敗しました。",
    MEETING_DELETE_FAILED: "会議の削除に失敗しました。",
    MEETING_TRANSCRIPT_CREATE_FAILED: "文字起こしの追加に失敗しました。",
    MEETING_SUMMARY_CREATE_FAILED: "要約の追加に失敗しました。",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "この会議にはまだ文字起こしがありません。",
    MEETING_PIPELINE_RUN_FAILED: "AI パイプラインの実行に失敗しました。",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "リアルタイム文字起こしの取得に失敗しました。",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "リアルタイム文字起こしの更新に失敗しました。",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "AI エージェントイベントの取得に失敗しました。",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "有効な AI エージェントセッションの取得に失敗しました。",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "AI エージェントが見つからないか、無効です。",
    MEETING_AGENT_INVOKE_FAILED: "AI エージェントの呼び出しに失敗しました。",
    MEETING_AGENT_SESSION_NOT_FOUND: "有効な AI エージェントセッションが見つかりません。",
    MEETING_AGENT_LEAVE_FAILED: "AI エージェントセッションの終了に失敗しました。",
    MEETING_AGENT_RESPONSE_FAILED: "AI エージェント応答の生成に失敗しました。",
    LIVEKIT_TOKEN_INPUT_REQUIRED: "roomName、participantName、participantIdentity は必須です。",
    LIVEKIT_TOKEN_GENERATE_FAILED: "LiveKit トークンの生成に失敗しました。",
    LIVEKIT_ROOMS_LIST_FAILED: "LiveKit ルーム一覧の取得に失敗しました。",
    LIVEKIT_ROOM_NAME_REQUIRED: "ルーム名を指定してください。",
    LIVEKIT_ROOM_CREATE_FAILED: "LiveKit ルームの作成に失敗しました。",
    LIVEKIT_ROOM_DELETE_FAILED: "LiveKit ルームの削除に失敗しました。",
    LIVEKIT_PARTICIPANTS_LIST_FAILED: "参加者一覧の取得に失敗しました。",
    LIVEKIT_RECORDING_START_FAILED: "録画の開始に失敗しました。",
    ROOM_AI_MEETING_RESOLVE_FAILED: "Room AI 用の会議解決に失敗しました。",
    ROOM_AI_STATUS_QUERY_REQUIRED: "status クエリが必要です。",
    ROOM_AI_MEETINGS_LIST_FAILED: "Room AI 用の会議一覧取得に失敗しました。",
    ROOM_AI_TRANSCRIPT_NOT_RECOGNIZED: "文字起こしを認識できませんでした。",
    ROOM_AI_TRANSCRIBE_FAILED: "音声文字起こしに失敗しました。",
    ROOM_AI_TRANSCRIPT_INGEST_FAILED: "文字起こしセグメントの取り込みに失敗しました。",
    ROOM_AI_STATUS_SYNC_FAILED: "会議ステータスの同期に失敗しました。",
    USERS_LIST_FAILED: "ユーザー一覧の取得に失敗しました。",
    USER_NOT_FOUND: "ユーザーが見つかりません。",
    CURRENT_USER_FETCH_FAILED: "現在のユーザー情報の取得に失敗しました。",
    CURRENT_USER_UPDATE_FAILED: "現在のユーザー情報の更新に失敗しました。",
    AUTH_SESSIONS_FETCH_FAILED: "認証セッション一覧の取得に失敗しました。",
    AUTH_SESSION_NOT_FOUND: "認証セッションが見つかりません。",
    AUTH_SESSION_REVOKE_FAILED: "認証セッションの失効に失敗しました。",
    USER_FETCH_FAILED: "ユーザー情報の取得に失敗しました。",
    USER_CREATE_FAILED: "ユーザーの作成に失敗しました。",
    USER_UPDATE_FAILED: "ユーザーの更新に失敗しました。",
    USER_DELETE_FAILED: "ユーザーの削除に失敗しました。",
  },
  en: {
    UNAUTHORIZED: "Authentication is required.",
    FORBIDDEN: "You are not allowed to perform this action.",
    NOT_FOUND: "The requested resource was not found.",
    RATE_LIMITED: "Too many attempts. Please try again later.",
    REGISTER_REJECTED: "Could not start account registration.",
    INVALID_TOKEN: "The verification token is invalid or expired.",
    INVALID_CREDENTIALS: "Invalid email or password.",
    INVALID_REFRESH_TOKEN: "Invalid refresh token.",
    GOOGLE_TOKEN_INVALID: "The Google token is invalid.",
    INTERNAL_SERVER_ERROR: "A server error occurred.",
    UNKNOWN_ERROR: "An unknown error occurred.",
    WIKI_PAGES_LIST_FAILED: "Failed to load pages.",
    WIKI_SEARCH_FAILED: "Search failed.",
    WIKI_PAGE_NOT_FOUND: "Page not found.",
    WIKI_PAGE_FORBIDDEN: "You do not have access to this page.",
    WIKI_PAGE_FETCH_FAILED: "Failed to load the page.",
    WIKI_PAGE_CREATE_FAILED: "Failed to create the page.",
    WIKI_PAGE_PARENT_CYCLE: "The parent page selection would create a cycle.",
    WIKI_PAGE_UPDATE_FAILED: "Failed to save the page.",
    WIKI_PAGE_DELETE_FAILED: "Failed to delete the page.",
    WIKI_BLOCK_CREATE_FAILED: "Failed to create the block.",
    WIKI_BLOCK_NOT_FOUND: "Block not found.",
    WIKI_BLOCK_UPDATE_FAILED: "Failed to update the block.",
    WIKI_BLOCK_DELETE_FAILED: "Failed to delete the block.",
    FILES_LIST_FAILED: "Failed to load files.",
    FILE_NOT_FOUND: "File not found.",
    FILE_FETCH_FAILED: "Failed to fetch the file.",
    FILE_MULTIPART_REQUIRED: "Multipart form data is required.",
    FILE_REQUIRED: "A file is required.",
    FILE_UPLOAD_FAILED: "Failed to upload the file.",
    FILE_PATH_INVALID: "The file path is invalid.",
    FILE_DOWNLOAD_URL_FAILED: "Failed to generate the download URL.",
    FILE_DELETE_FAILED: "Failed to delete the file.",
    ADMIN_GROUPS_LIST_FAILED: "Failed to load groups.",
    ADMIN_AGENTS_LIST_FAILED: "Failed to load agents.",
    ADMIN_AGENT_CREATE_FAILED: "Failed to create the agent.",
    ADMIN_AGENT_NOT_FOUND: "Agent not found.",
    ADMIN_AGENT_UPDATE_FAILED: "Failed to update the agent.",
    ADMIN_GROUP_NAME_CONFLICT: "A group with the same name already exists.",
    ADMIN_GROUP_CREATE_FAILED: "Failed to create the group.",
    ADMIN_GROUP_NOT_FOUND: "Group not found.",
    ADMIN_GROUP_FETCH_FAILED: "Failed to fetch the group.",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "System groups cannot be modified.",
    ADMIN_GROUP_UPDATE_FAILED: "Failed to update the group.",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "System groups cannot be deleted.",
    ADMIN_GROUP_DELETE_FAILED: "Failed to delete the group.",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "Failed to load group members.",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "Failed to add group members.",
    ADMIN_MEMBERSHIP_NOT_FOUND: "Membership not found.",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "Failed to delete the membership.",
    ADMIN_USERS_LIST_FAILED: "Failed to load users.",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "Failed to update user memberships.",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "Failed to load page permissions.",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "Failed to update page permissions.",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "Page permission not found.",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "Failed to delete the page permission.",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "Failed to load page inheritance settings.",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "Failed to update page inheritance settings.",
    ADMIN_KPI_OVERVIEW_FAILED: "Failed to load KPI.",
    MEETINGS_LIST_FAILED: "Failed to load meetings.",
    MEETING_NOT_FOUND: "Meeting not found.",
    MEETING_FORBIDDEN: "You do not have access to this meeting.",
    MEETING_FETCH_FAILED: "Failed to load the meeting.",
    MEETING_CREATE_FAILED: "Failed to create the meeting.",
    MEETING_UPDATE_FAILED: "Failed to update the meeting.",
    MEETING_DELETE_FAILED: "Failed to delete the meeting.",
    MEETING_TRANSCRIPT_CREATE_FAILED: "Failed to add the transcript.",
    MEETING_SUMMARY_CREATE_FAILED: "Failed to add the summary.",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "No transcripts are available for this meeting yet.",
    MEETING_PIPELINE_RUN_FAILED: "Failed to run the AI pipeline.",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "Failed to fetch realtime transcripts.",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "Failed to update the realtime transcript.",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "Failed to fetch meeting agent events.",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "Failed to fetch active meeting agent sessions.",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "The agent was not found or is inactive.",
    MEETING_AGENT_INVOKE_FAILED: "Failed to invoke the agent.",
    MEETING_AGENT_SESSION_NOT_FOUND: "Active agent session not found.",
    MEETING_AGENT_LEAVE_FAILED: "Failed to end the agent session.",
    MEETING_AGENT_RESPONSE_FAILED: "Failed to generate the agent response.",
    LIVEKIT_TOKEN_INPUT_REQUIRED:
      "roomName, participantName, and participantIdentity are required.",
    LIVEKIT_TOKEN_GENERATE_FAILED: "Failed to generate the LiveKit token.",
    LIVEKIT_ROOMS_LIST_FAILED: "Failed to load LiveKit rooms.",
    LIVEKIT_ROOM_NAME_REQUIRED: "Room name is required.",
    LIVEKIT_ROOM_CREATE_FAILED: "Failed to create the LiveKit room.",
    LIVEKIT_ROOM_DELETE_FAILED: "Failed to delete the LiveKit room.",
    LIVEKIT_PARTICIPANTS_LIST_FAILED: "Failed to load participants.",
    LIVEKIT_RECORDING_START_FAILED: "Failed to start recording.",
    ROOM_AI_MEETING_RESOLVE_FAILED: "Failed to resolve the Room AI meeting.",
    ROOM_AI_STATUS_QUERY_REQUIRED: "The status query is required.",
    ROOM_AI_MEETINGS_LIST_FAILED: "Failed to load Room AI meetings.",
    ROOM_AI_TRANSCRIPT_NOT_RECOGNIZED: "No transcript could be recognized.",
    ROOM_AI_TRANSCRIBE_FAILED: "Failed to transcribe the audio.",
    ROOM_AI_TRANSCRIPT_INGEST_FAILED: "Failed to ingest the transcript segment.",
    ROOM_AI_STATUS_SYNC_FAILED: "Failed to sync the meeting status.",
    USERS_LIST_FAILED: "Failed to fetch users.",
    USER_NOT_FOUND: "User not found.",
    CURRENT_USER_FETCH_FAILED: "Failed to fetch the current user.",
    CURRENT_USER_UPDATE_FAILED: "Failed to update the current user.",
    AUTH_SESSIONS_FETCH_FAILED: "Failed to load authentication sessions.",
    AUTH_SESSION_NOT_FOUND: "Authentication session not found.",
    AUTH_SESSION_REVOKE_FAILED: "Failed to revoke the authentication session.",
    USER_FETCH_FAILED: "Failed to fetch the user.",
    USER_CREATE_FAILED: "Failed to create the user.",
    USER_UPDATE_FAILED: "Failed to update the user.",
    USER_DELETE_FAILED: "Failed to delete the user.",
  },
  "zh-CN": {
    UNAUTHORIZED: "需要登录。",
    FORBIDDEN: "您无权执行此操作。",
    NOT_FOUND: "未找到请求的资源。",
    RATE_LIMITED: "尝试次数过多，请稍后重试。",
    REGISTER_REJECTED: "无法开始注册账号。",
    INVALID_TOKEN: "验证令牌无效或已过期。",
    INVALID_CREDENTIALS: "邮箱或密码不正确。",
    INVALID_REFRESH_TOKEN: "刷新令牌无效。",
    GOOGLE_TOKEN_INVALID: "Google 令牌无效。",
    INTERNAL_SERVER_ERROR: "发生服务器错误。",
    UNKNOWN_ERROR: "发生未知错误。",
    WIKI_PAGES_LIST_FAILED: "加载页面列表失败。",
    WIKI_SEARCH_FAILED: "搜索失败。",
    WIKI_PAGE_NOT_FOUND: "未找到页面。",
    WIKI_PAGE_FORBIDDEN: "您无权访问此页面。",
    WIKI_PAGE_FETCH_FAILED: "加载页面失败。",
    WIKI_PAGE_CREATE_FAILED: "创建页面失败。",
    WIKI_PAGE_PARENT_CYCLE: "父页面设置会导致循环引用。",
    WIKI_PAGE_UPDATE_FAILED: "更新页面失败。",
    WIKI_PAGE_DELETE_FAILED: "删除页面失败。",
    WIKI_BLOCK_CREATE_FAILED: "创建区块失败。",
    WIKI_BLOCK_NOT_FOUND: "未找到区块。",
    WIKI_BLOCK_UPDATE_FAILED: "更新区块失败。",
    WIKI_BLOCK_DELETE_FAILED: "删除区块失败。",
    FILES_LIST_FAILED: "加载文件列表失败。",
    FILE_NOT_FOUND: "未找到文件。",
    FILE_FETCH_FAILED: "获取文件失败。",
    FILE_MULTIPART_REQUIRED: "请使用 multipart/form-data 提交。",
    FILE_REQUIRED: "请选择文件。",
    FILE_UPLOAD_FAILED: "上传文件失败。",
    FILE_PATH_INVALID: "文件路径无效。",
    FILE_DOWNLOAD_URL_FAILED: "生成下载链接失败。",
    FILE_DELETE_FAILED: "删除文件失败。",
    ADMIN_GROUPS_LIST_FAILED: "加载分组列表失败。",
    ADMIN_AGENTS_LIST_FAILED: "加载 AI 助手列表失败。",
    ADMIN_AGENT_CREATE_FAILED: "创建 AI 助手失败。",
    ADMIN_AGENT_NOT_FOUND: "未找到 AI 助手。",
    ADMIN_AGENT_UPDATE_FAILED: "更新 AI 助手失败。",
    ADMIN_GROUP_NAME_CONFLICT: "已存在同名分组。",
    ADMIN_GROUP_CREATE_FAILED: "创建分组失败。",
    ADMIN_GROUP_NOT_FOUND: "未找到分组。",
    ADMIN_GROUP_FETCH_FAILED: "获取分组信息失败。",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "系统分组无法修改。",
    ADMIN_GROUP_UPDATE_FAILED: "更新分组失败。",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "系统分组无法删除。",
    ADMIN_GROUP_DELETE_FAILED: "删除分组失败。",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "加载分组成员失败。",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "添加分组成员失败。",
    ADMIN_MEMBERSHIP_NOT_FOUND: "未找到成员关系。",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "删除成员关系失败。",
    ADMIN_USERS_LIST_FAILED: "加载用户列表失败。",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "更新用户分组失败。",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "加载页面权限失败。",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "更新页面权限失败。",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "未找到页面权限。",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "删除页面权限失败。",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "加载页面继承设置失败。",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "更新页面继承设置失败。",
    ADMIN_KPI_OVERVIEW_FAILED: "加载 KPI 失败。",
    MEETINGS_LIST_FAILED: "加载会议列表失败。",
    MEETING_NOT_FOUND: "未找到会议。",
    MEETING_FORBIDDEN: "您无权访问此会议。",
    MEETING_FETCH_FAILED: "加载会议信息失败。",
    MEETING_CREATE_FAILED: "创建会议失败。",
    MEETING_UPDATE_FAILED: "更新会议失败。",
    MEETING_DELETE_FAILED: "删除会议失败。",
    MEETING_TRANSCRIPT_CREATE_FAILED: "添加转录失败。",
    MEETING_SUMMARY_CREATE_FAILED: "添加摘要失败。",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "此会议暂无可用转录。",
    MEETING_PIPELINE_RUN_FAILED: "运行 AI 流程失败。",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "获取实时转录失败。",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "更新实时转录失败。",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "获取 AI 助手事件失败。",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "获取活跃 AI 助手会话失败。",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "未找到 AI 助手，或其已停用。",
    MEETING_AGENT_INVOKE_FAILED: "调用 AI 助手失败。",
    MEETING_AGENT_SESSION_NOT_FOUND: "未找到活跃的 AI 助手会话。",
    MEETING_AGENT_LEAVE_FAILED: "结束 AI 助手会话失败。",
    MEETING_AGENT_RESPONSE_FAILED: "生成 AI 助手回复失败。",
    LIVEKIT_TOKEN_INPUT_REQUIRED: "必须提供 roomName、participantName 和 participantIdentity。",
    LIVEKIT_TOKEN_GENERATE_FAILED: "生成 LiveKit 令牌失败。",
    LIVEKIT_ROOMS_LIST_FAILED: "加载 LiveKit 房间列表失败。",
    LIVEKIT_ROOM_NAME_REQUIRED: "请输入房间名称。",
    LIVEKIT_ROOM_CREATE_FAILED: "创建 LiveKit 房间失败。",
    LIVEKIT_ROOM_DELETE_FAILED: "删除 LiveKit 房间失败。",
    LIVEKIT_PARTICIPANTS_LIST_FAILED: "加载参与者列表失败。",
    LIVEKIT_RECORDING_START_FAILED: "开始录制失败。",
    ROOM_AI_MEETING_RESOLVE_FAILED: "解析 Room AI 对应会议失败。",
    ROOM_AI_STATUS_QUERY_REQUIRED: "必须提供 status 查询参数。",
    ROOM_AI_MEETINGS_LIST_FAILED: "加载 Room AI 会议列表失败。",
    ROOM_AI_TRANSCRIPT_NOT_RECOGNIZED: "未能识别出转录内容。",
    ROOM_AI_TRANSCRIBE_FAILED: "音频转录失败。",
    ROOM_AI_TRANSCRIPT_INGEST_FAILED: "写入转录片段失败。",
    ROOM_AI_STATUS_SYNC_FAILED: "同步会议状态失败。",
    USERS_LIST_FAILED: "获取用户列表失败。",
    USER_NOT_FOUND: "未找到用户。",
    CURRENT_USER_FETCH_FAILED: "获取当前用户信息失败。",
    CURRENT_USER_UPDATE_FAILED: "更新当前用户信息失败。",
    AUTH_SESSIONS_FETCH_FAILED: "获取认证会话失败。",
    AUTH_SESSION_NOT_FOUND: "未找到认证会话。",
    AUTH_SESSION_REVOKE_FAILED: "撤销认证会话失败。",
    USER_FETCH_FAILED: "获取用户信息失败。",
    USER_CREATE_FAILED: "创建用户失败。",
    USER_UPDATE_FAILED: "更新用户失败。",
    USER_DELETE_FAILED: "删除用户失败。",
  },
  ko: {
    UNAUTHORIZED: "인증이 필요합니다.",
    FORBIDDEN: "이 작업을 수행할 권한이 없습니다.",
    NOT_FOUND: "요청한 리소스를 찾을 수 없습니다.",
    RATE_LIMITED: "시도가 너무 많습니다. 잠시 후 다시 시도해 주세요.",
    REGISTER_REJECTED: "계정 등록을 시작할 수 없습니다.",
    INVALID_TOKEN: "확인 토큰이 유효하지 않거나 만료되었습니다.",
    INVALID_CREDENTIALS: "이메일 또는 비밀번호가 올바르지 않습니다.",
    INVALID_REFRESH_TOKEN: "리프레시 토큰이 유효하지 않습니다.",
    GOOGLE_TOKEN_INVALID: "Google 토큰이 유효하지 않습니다.",
    INTERNAL_SERVER_ERROR: "서버 오류가 발생했습니다.",
    UNKNOWN_ERROR: "알 수 없는 오류가 발생했습니다.",
    WIKI_PAGES_LIST_FAILED: "페이지 목록을 불러오지 못했습니다.",
    WIKI_SEARCH_FAILED: "검색에 실패했습니다.",
    WIKI_PAGE_NOT_FOUND: "페이지를 찾을 수 없습니다.",
    WIKI_PAGE_FORBIDDEN: "이 페이지에 접근할 권한이 없습니다.",
    WIKI_PAGE_FETCH_FAILED: "페이지를 불러오지 못했습니다.",
    WIKI_PAGE_CREATE_FAILED: "페이지를 만들지 못했습니다.",
    WIKI_PAGE_PARENT_CYCLE: "상위 페이지 설정에 순환 참조가 발생합니다.",
    WIKI_PAGE_UPDATE_FAILED: "페이지를 저장하지 못했습니다.",
    WIKI_PAGE_DELETE_FAILED: "페이지를 삭제하지 못했습니다.",
    WIKI_BLOCK_CREATE_FAILED: "블록을 만들지 못했습니다.",
    WIKI_BLOCK_NOT_FOUND: "블록을 찾을 수 없습니다.",
    WIKI_BLOCK_UPDATE_FAILED: "블록을 수정하지 못했습니다.",
    WIKI_BLOCK_DELETE_FAILED: "블록을 삭제하지 못했습니다.",
    FILES_LIST_FAILED: "파일 목록을 불러오지 못했습니다.",
    FILE_NOT_FOUND: "파일을 찾을 수 없습니다.",
    FILE_FETCH_FAILED: "파일을 가져오지 못했습니다.",
    FILE_MULTIPART_REQUIRED: "multipart/form-data 형식으로 전송해 주세요.",
    FILE_REQUIRED: "파일이 필요합니다.",
    FILE_UPLOAD_FAILED: "파일 업로드에 실패했습니다.",
    FILE_PATH_INVALID: "파일 경로가 올바르지 않습니다.",
    FILE_DOWNLOAD_URL_FAILED: "다운로드 URL 생성에 실패했습니다.",
    FILE_DELETE_FAILED: "파일 삭제에 실패했습니다.",
    ADMIN_GROUPS_LIST_FAILED: "그룹 목록을 불러오지 못했습니다.",
    ADMIN_AGENTS_LIST_FAILED: "AI 도우미 목록을 불러오지 못했습니다.",
    ADMIN_AGENT_CREATE_FAILED: "AI 도우미를 만들지 못했습니다.",
    ADMIN_AGENT_NOT_FOUND: "AI 도우미를 찾을 수 없습니다.",
    ADMIN_AGENT_UPDATE_FAILED: "AI 도우미를 수정하지 못했습니다.",
    ADMIN_GROUP_NAME_CONFLICT: "같은 이름의 그룹이 이미 존재합니다.",
    ADMIN_GROUP_CREATE_FAILED: "그룹을 만들지 못했습니다.",
    ADMIN_GROUP_NOT_FOUND: "그룹을 찾을 수 없습니다.",
    ADMIN_GROUP_FETCH_FAILED: "그룹 정보를 가져오지 못했습니다.",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "시스템 그룹은 수정할 수 없습니다.",
    ADMIN_GROUP_UPDATE_FAILED: "그룹을 수정하지 못했습니다.",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "시스템 그룹은 삭제할 수 없습니다.",
    ADMIN_GROUP_DELETE_FAILED: "그룹을 삭제하지 못했습니다.",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "그룹 멤버를 불러오지 못했습니다.",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "그룹 멤버를 추가하지 못했습니다.",
    ADMIN_MEMBERSHIP_NOT_FOUND: "멤버십을 찾을 수 없습니다.",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "멤버십을 삭제하지 못했습니다.",
    ADMIN_USERS_LIST_FAILED: "사용자 목록을 불러오지 못했습니다.",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "사용자 그룹을 수정하지 못했습니다.",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "페이지 권한을 불러오지 못했습니다.",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "페이지 권한을 수정하지 못했습니다.",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "페이지 권한을 찾을 수 없습니다.",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "페이지 권한을 삭제하지 못했습니다.",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "페이지 상속 설정을 불러오지 못했습니다.",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "페이지 상속 설정을 수정하지 못했습니다.",
    ADMIN_KPI_OVERVIEW_FAILED: "KPI 를 불러오지 못했습니다.",
    MEETINGS_LIST_FAILED: "회의 목록을 불러오지 못했습니다.",
    MEETING_NOT_FOUND: "회의를 찾을 수 없습니다.",
    MEETING_FORBIDDEN: "이 회의에 접근할 권한이 없습니다.",
    MEETING_FETCH_FAILED: "회의 정보를 불러오지 못했습니다.",
    MEETING_CREATE_FAILED: "회의를 만들지 못했습니다.",
    MEETING_UPDATE_FAILED: "회의를 수정하지 못했습니다.",
    MEETING_DELETE_FAILED: "회의를 삭제하지 못했습니다.",
    MEETING_TRANSCRIPT_CREATE_FAILED: "전사 내용을 추가하지 못했습니다.",
    MEETING_SUMMARY_CREATE_FAILED: "요약을 추가하지 못했습니다.",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "이 회의에는 아직 전사 내용이 없습니다.",
    MEETING_PIPELINE_RUN_FAILED: "AI 파이프라인 실행에 실패했습니다.",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "실시간 전사를 가져오지 못했습니다.",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "실시간 전사를 업데이트하지 못했습니다.",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "AI 도우미 이벤트를 가져오지 못했습니다.",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "활성 AI 도우미 세션을 가져오지 못했습니다.",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "AI 도우미를 찾을 수 없거나 비활성 상태입니다.",
    MEETING_AGENT_INVOKE_FAILED: "AI 도우미 호출에 실패했습니다.",
    MEETING_AGENT_SESSION_NOT_FOUND: "활성 AI 도우미 세션을 찾을 수 없습니다.",
    MEETING_AGENT_LEAVE_FAILED: "AI 도우미 세션 종료에 실패했습니다.",
    MEETING_AGENT_RESPONSE_FAILED: "AI 도우미 응답 생성에 실패했습니다.",
    LIVEKIT_TOKEN_INPUT_REQUIRED: "roomName, participantName, participantIdentity 값이 필요합니다.",
    LIVEKIT_TOKEN_GENERATE_FAILED: "LiveKit 토큰 생성에 실패했습니다.",
    LIVEKIT_ROOMS_LIST_FAILED: "LiveKit 방 목록을 불러오지 못했습니다.",
    LIVEKIT_ROOM_NAME_REQUIRED: "방 이름이 필요합니다.",
    LIVEKIT_ROOM_CREATE_FAILED: "LiveKit 방 생성에 실패했습니다.",
    LIVEKIT_ROOM_DELETE_FAILED: "LiveKit 방 삭제에 실패했습니다.",
    LIVEKIT_PARTICIPANTS_LIST_FAILED: "참가자 목록을 불러오지 못했습니다.",
    LIVEKIT_RECORDING_START_FAILED: "녹화 시작에 실패했습니다.",
    ROOM_AI_MEETING_RESOLVE_FAILED: "Room AI 회의 조회에 실패했습니다.",
    ROOM_AI_STATUS_QUERY_REQUIRED: "status 쿼리가 필요합니다.",
    ROOM_AI_MEETINGS_LIST_FAILED: "Room AI 회의 목록을 불러오지 못했습니다.",
    ROOM_AI_TRANSCRIPT_NOT_RECOGNIZED: "전사 내용을 인식하지 못했습니다.",
    ROOM_AI_TRANSCRIBE_FAILED: "오디오 전사에 실패했습니다.",
    ROOM_AI_TRANSCRIPT_INGEST_FAILED: "전사 세그먼트 저장에 실패했습니다.",
    ROOM_AI_STATUS_SYNC_FAILED: "회의 상태 동기화에 실패했습니다.",
    USERS_LIST_FAILED: "사용자 목록을 가져오지 못했습니다.",
    USER_NOT_FOUND: "사용자를 찾을 수 없습니다.",
    CURRENT_USER_FETCH_FAILED: "현재 사용자 정보를 가져오지 못했습니다.",
    CURRENT_USER_UPDATE_FAILED: "현재 사용자 정보를 수정하지 못했습니다.",
    AUTH_SESSIONS_FETCH_FAILED: "인증 세션을 불러오지 못했습니다.",
    AUTH_SESSION_NOT_FOUND: "인증 세션을 찾을 수 없습니다.",
    AUTH_SESSION_REVOKE_FAILED: "인증 세션 해제에 실패했습니다.",
    USER_FETCH_FAILED: "사용자 정보를 가져오지 못했습니다.",
    USER_CREATE_FAILED: "사용자를 만들지 못했습니다.",
    USER_UPDATE_FAILED: "사용자를 수정하지 못했습니다.",
    USER_DELETE_FAILED: "사용자를 삭제하지 못했습니다.",
  },
};

function isApiErrorLike(error: unknown): error is ApiErrorLike {
  if (!error || typeof error !== "object") {
    return false;
  }

  const candidate = error as Partial<ApiErrorLike> & { name?: unknown };
  return (
    typeof candidate.message === "string" &&
    (typeof candidate.code === "string" ||
      typeof candidate.detail === "string" ||
      candidate.name === "ApiError")
  );
}

export function getApiErrorMessage(
  error: unknown,
  locale: SupportedLocale,
  fallbackMessage: string
) {
  if (isApiErrorLike(error)) {
    const code = error.code;
    if (code) {
      const localized = messagesByLocale[locale][code] ?? messagesByLocale[defaultLocale][code];
      if (localized) {
        return localized;
      }
    }

    return (error.detail ?? error.message) || fallbackMessage;
  }

  return error instanceof Error ? error.message : fallbackMessage;
}

export function useApiErrorMessage() {
  const locale = useLocale();
  return useCallback(
    (error: unknown, fallbackMessage: string) => getApiErrorMessage(error, locale, fallbackMessage),
    [locale]
  );
}
