"use client";

import { ApiError } from "@/lib/api";
import type { SupportedLocale } from "@/lib/i18n";
import { defaultLocale, useLocale } from "@/lib/i18n";
import { useCallback } from "react";

type LocalizedMessages = Record<string, string>;

const messagesByLocale: Record<SupportedLocale, LocalizedMessages> = {
  ja: {
    UNAUTHORIZED: "認証が必要です。",
    FORBIDDEN: "この操作は許可されていません。",
    NOT_FOUND: "対象が見つかりません。",
    RATE_LIMITED: "一定時間に試行回数が多すぎます。しばらく待ってから再試行してください。",
    REGISTER_REJECTED: "アカウント登録を開始できませんでした。",
    INVALID_TOKEN: "確認トークンが無効か期限切れです。",
    INVALID_CREDENTIALS: "メールアドレスまたはパスワードが正しくありません。",
    INVALID_REFRESH_TOKEN: "リフレッシュトークンが無効です。",
    INTERNAL_SERVER_ERROR: "サーバーエラーが発生しました。",
    UNKNOWN_ERROR: "不明なエラーが発生しました。",
    WIKI_PAGES_LIST_FAILED: "ページの読み込みに失敗しました。",
    WIKI_SEARCH_FAILED: "検索に失敗しました。",
    WIKI_PAGE_NOT_FOUND: "ページが見つかりません。",
    WIKI_PAGE_FORBIDDEN: "このページを表示する権限がありません。",
    WIKI_PAGE_FETCH_FAILED: "ページの読み込みに失敗しました。",
    WIKI_PAGE_CREATE_FAILED: "ページの作成に失敗しました。",
    WIKI_PAGE_PARENT_CYCLE: "親ページの設定が循環しています。",
    WIKI_PAGE_UPDATE_FAILED: "ページの保存に失敗しました。",
    WIKI_PAGE_DELETE_FAILED: "ページの削除に失敗しました。",
    WIKI_BLOCK_CREATE_FAILED: "ブロックの作成に失敗しました。",
    WIKI_BLOCK_NOT_FOUND: "ブロックが見つかりません。",
    WIKI_BLOCK_UPDATE_FAILED: "ブロックの更新に失敗しました。",
    WIKI_BLOCK_DELETE_FAILED: "ブロックの削除に失敗しました。",
    ADMIN_GROUPS_LIST_FAILED: "グループ一覧の取得に失敗しました。",
    ADMIN_AGENTS_LIST_FAILED: "エージェント一覧の取得に失敗しました。",
    ADMIN_AGENT_CREATE_FAILED: "エージェントの作成に失敗しました。",
    ADMIN_AGENT_NOT_FOUND: "エージェントが見つかりません。",
    ADMIN_AGENT_UPDATE_FAILED: "エージェントの更新に失敗しました。",
    ADMIN_GROUP_NAME_CONFLICT: "同じ名前のグループが既に存在します。",
    ADMIN_GROUP_CREATE_FAILED: "グループの作成に失敗しました。",
    ADMIN_GROUP_NOT_FOUND: "グループが見つかりません。",
    ADMIN_GROUP_FETCH_FAILED: "グループの取得に失敗しました。",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "システムグループは変更できません。",
    ADMIN_GROUP_UPDATE_FAILED: "グループの更新に失敗しました。",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "システムグループは削除できません。",
    ADMIN_GROUP_DELETE_FAILED: "グループの削除に失敗しました。",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "グループメンバーの取得に失敗しました。",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "グループメンバーの追加に失敗しました。",
    ADMIN_MEMBERSHIP_NOT_FOUND: "対象の所属情報が見つかりません。",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "所属情報の削除に失敗しました。",
    ADMIN_USERS_LIST_FAILED: "ユーザー一覧の取得に失敗しました。",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "ユーザー所属の更新に失敗しました。",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "ページ権限の取得に失敗しました。",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "ページ権限の更新に失敗しました。",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "ページ権限が見つかりません。",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "ページ権限の削除に失敗しました。",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "ページ権限の継承設定の取得に失敗しました。",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "ページ権限の継承設定の更新に失敗しました。",
    ADMIN_KPI_OVERVIEW_FAILED: "KPI の読み込みに失敗しました。",
    MEETINGS_LIST_FAILED: "会議の読み込みに失敗しました。",
    MEETING_NOT_FOUND: "会議が見つかりません。",
    MEETING_FORBIDDEN: "この会議にアクセスする権限がありません。",
    MEETING_FETCH_FAILED: "会議の読み込みに失敗しました。",
    MEETING_CREATE_FAILED: "会議の作成に失敗しました。",
    MEETING_UPDATE_FAILED: "会議の更新に失敗しました。",
    MEETING_DELETE_FAILED: "会議の削除に失敗しました。",
    MEETING_TRANSCRIPT_CREATE_FAILED: "文字起こしの追加に失敗しました。",
    MEETING_SUMMARY_CREATE_FAILED: "要約の追加に失敗しました。",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "この会議には文字起こしがまだありません。",
    MEETING_PIPELINE_RUN_FAILED: "AI パイプラインの実行に失敗しました。",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "リアルタイム文字起こしの取得に失敗しました。",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "リアルタイム文字起こしの更新に失敗しました。",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "エージェントイベントの取得に失敗しました。",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "アクティブなエージェントセッションの取得に失敗しました。",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "エージェントが見つからないか、無効です。",
    MEETING_AGENT_INVOKE_FAILED: "エージェントの呼び出しに失敗しました。",
    MEETING_AGENT_SESSION_NOT_FOUND: "アクティブなエージェントセッションが見つかりません。",
    MEETING_AGENT_LEAVE_FAILED: "エージェントの終了に失敗しました。",
    MEETING_AGENT_RESPONSE_FAILED: "エージェント応答の生成に失敗しました.",
  },
  en: {
    UNAUTHORIZED: "Authentication is required.",
    FORBIDDEN: "You are not allowed to perform this action.",
    NOT_FOUND: "The requested resource was not found.",
    RATE_LIMITED: "Too many attempts. Please try again later.",
    REGISTER_REJECTED: "Could not start account registration.",
    INVALID_TOKEN: "The verification token is invalid or expired.",
    INVALID_CREDENTIALS: "Invalid email or password.",
    INVALID_REFRESH_TOKEN: "Invalid refresh token.",
    INTERNAL_SERVER_ERROR: "A server error occurred.",
    UNKNOWN_ERROR: "An unknown error occurred.",
    WIKI_PAGES_LIST_FAILED: "Failed to load pages.",
    WIKI_SEARCH_FAILED: "Search failed.",
    WIKI_PAGE_NOT_FOUND: "Page not found.",
    WIKI_PAGE_FORBIDDEN: "You do not have access to this page.",
    WIKI_PAGE_FETCH_FAILED: "Failed to load the page.",
    WIKI_PAGE_CREATE_FAILED: "Failed to create the page.",
    WIKI_PAGE_PARENT_CYCLE: "The parent page selection would create a cycle.",
    WIKI_PAGE_UPDATE_FAILED: "Failed to save the page.",
    WIKI_PAGE_DELETE_FAILED: "Failed to delete the page.",
    WIKI_BLOCK_CREATE_FAILED: "Failed to create the block.",
    WIKI_BLOCK_NOT_FOUND: "Block not found.",
    WIKI_BLOCK_UPDATE_FAILED: "Failed to update the block.",
    WIKI_BLOCK_DELETE_FAILED: "Failed to delete the block.",
    ADMIN_GROUPS_LIST_FAILED: "Failed to load groups.",
    ADMIN_AGENTS_LIST_FAILED: "Failed to load agents.",
    ADMIN_AGENT_CREATE_FAILED: "Failed to create the agent.",
    ADMIN_AGENT_NOT_FOUND: "Agent not found.",
    ADMIN_AGENT_UPDATE_FAILED: "Failed to update the agent.",
    ADMIN_GROUP_NAME_CONFLICT: "A group with the same name already exists.",
    ADMIN_GROUP_CREATE_FAILED: "Failed to create the group.",
    ADMIN_GROUP_NOT_FOUND: "Group not found.",
    ADMIN_GROUP_FETCH_FAILED: "Failed to fetch the group.",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "System groups cannot be modified.",
    ADMIN_GROUP_UPDATE_FAILED: "Failed to update the group.",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "System groups cannot be deleted.",
    ADMIN_GROUP_DELETE_FAILED: "Failed to delete the group.",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "Failed to load group members.",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "Failed to add group members.",
    ADMIN_MEMBERSHIP_NOT_FOUND: "Membership not found.",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "Failed to delete the membership.",
    ADMIN_USERS_LIST_FAILED: "Failed to load users.",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "Failed to update user memberships.",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "Failed to load page permissions.",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "Failed to update page permissions.",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "Page permission not found.",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "Failed to delete the page permission.",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "Failed to load page inheritance settings.",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "Failed to update page inheritance settings.",
    ADMIN_KPI_OVERVIEW_FAILED: "Failed to load KPI.",
    MEETINGS_LIST_FAILED: "Failed to load meetings.",
    MEETING_NOT_FOUND: "Meeting not found.",
    MEETING_FORBIDDEN: "You do not have access to this meeting.",
    MEETING_FETCH_FAILED: "Failed to load the meeting.",
    MEETING_CREATE_FAILED: "Failed to create the meeting.",
    MEETING_UPDATE_FAILED: "Failed to update the meeting.",
    MEETING_DELETE_FAILED: "Failed to delete the meeting.",
    MEETING_TRANSCRIPT_CREATE_FAILED: "Failed to add the transcript.",
    MEETING_SUMMARY_CREATE_FAILED: "Failed to add the summary.",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "No transcripts are available for this meeting yet.",
    MEETING_PIPELINE_RUN_FAILED: "Failed to run the AI pipeline.",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "Failed to fetch realtime transcripts.",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "Failed to update the realtime transcript.",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "Failed to fetch meeting agent events.",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "Failed to fetch active meeting agent sessions.",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "The agent was not found or is inactive.",
    MEETING_AGENT_INVOKE_FAILED: "Failed to invoke the agent.",
    MEETING_AGENT_SESSION_NOT_FOUND: "Active agent session not found.",
    MEETING_AGENT_LEAVE_FAILED: "Failed to end the agent session.",
    MEETING_AGENT_RESPONSE_FAILED: "Failed to generate the agent response.",
  },
  "zh-CN": {
    UNAUTHORIZED: "需要先登录。",
    FORBIDDEN: "你没有执行此操作的权限。",
    NOT_FOUND: "未找到请求的资源。",
    RATE_LIMITED: "尝试次数过多，请稍后再试。",
    REGISTER_REJECTED: "无法开始账号注册。",
    INVALID_TOKEN: "验证令牌无效或已过期。",
    INVALID_CREDENTIALS: "邮箱或密码不正确。",
    INVALID_REFRESH_TOKEN: "刷新令牌无效。",
    INTERNAL_SERVER_ERROR: "发生了服务器错误。",
    UNKNOWN_ERROR: "发生未知错误。",
    WIKI_PAGES_LIST_FAILED: "加载页面失败。",
    WIKI_SEARCH_FAILED: "搜索失败。",
    WIKI_PAGE_NOT_FOUND: "未找到页面。",
    WIKI_PAGE_FORBIDDEN: "你没有查看此页面的权限。",
    WIKI_PAGE_FETCH_FAILED: "加载页面失败。",
    WIKI_PAGE_CREATE_FAILED: "创建页面失败。",
    WIKI_PAGE_PARENT_CYCLE: "父页面设置会形成循环引用。",
    WIKI_PAGE_UPDATE_FAILED: "保存页面失败。",
    WIKI_PAGE_DELETE_FAILED: "删除页面失败。",
    WIKI_BLOCK_CREATE_FAILED: "创建区块失败。",
    WIKI_BLOCK_NOT_FOUND: "未找到区块。",
    WIKI_BLOCK_UPDATE_FAILED: "更新区块失败。",
    WIKI_BLOCK_DELETE_FAILED: "删除区块失败。",
    ADMIN_GROUPS_LIST_FAILED: "加载分组列表失败。",
    ADMIN_AGENTS_LIST_FAILED: "加载 agent 列表失败。",
    ADMIN_AGENT_CREATE_FAILED: "创建 agent 失败。",
    ADMIN_AGENT_NOT_FOUND: "未找到 agent。",
    ADMIN_AGENT_UPDATE_FAILED: "更新 agent 失败。",
    ADMIN_GROUP_NAME_CONFLICT: "已存在同名分组。",
    ADMIN_GROUP_CREATE_FAILED: "创建分组失败。",
    ADMIN_GROUP_NOT_FOUND: "未找到分组。",
    ADMIN_GROUP_FETCH_FAILED: "获取分组失败。",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "系统分组不能修改。",
    ADMIN_GROUP_UPDATE_FAILED: "更新分组失败。",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "系统分组不能删除。",
    ADMIN_GROUP_DELETE_FAILED: "删除分组失败。",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "获取分组成员失败。",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "添加分组成员失败。",
    ADMIN_MEMBERSHIP_NOT_FOUND: "未找到所属关系。",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "删除所属关系失败。",
    ADMIN_USERS_LIST_FAILED: "加载用户列表失败。",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "更新用户归属失败。",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "获取页面权限失败。",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "更新页面权限失败。",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "未找到页面权限。",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "删除页面权限失败。",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "获取页面继承设置失败。",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "更新页面继承设置失败。",
    ADMIN_KPI_OVERVIEW_FAILED: "加载 KPI 失败。",
    MEETINGS_LIST_FAILED: "加载会议失败。",
    MEETING_NOT_FOUND: "未找到会议。",
    MEETING_FORBIDDEN: "你没有访问此会议的权限。",
    MEETING_FETCH_FAILED: "加载会议失败。",
    MEETING_CREATE_FAILED: "创建会议失败。",
    MEETING_UPDATE_FAILED: "更新会议失败。",
    MEETING_DELETE_FAILED: "删除会议失败。",
    MEETING_TRANSCRIPT_CREATE_FAILED: "添加转录失败。",
    MEETING_SUMMARY_CREATE_FAILED: "添加总结失败。",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "此会议还没有可用的转录内容。",
    MEETING_PIPELINE_RUN_FAILED: "运行 AI 流水线失败。",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "获取实时转录失败。",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "更新实时转录失败。",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "获取 agent 事件失败。",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "获取活动 agent 会话失败。",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "未找到 agent，或 agent 未启用。",
    MEETING_AGENT_INVOKE_FAILED: "调用 agent 失败。",
    MEETING_AGENT_SESSION_NOT_FOUND: "未找到活动的 agent 会话。",
    MEETING_AGENT_LEAVE_FAILED: "结束 agent 会话失败。",
    MEETING_AGENT_RESPONSE_FAILED: "生成 agent 回复失败。",
  },
  ko: {
    UNAUTHORIZED: "인증이 필요합니다.",
    FORBIDDEN: "이 작업을 수행할 권한이 없습니다.",
    NOT_FOUND: "요청한 대상을 찾을 수 없습니다.",
    RATE_LIMITED: "시도 횟수가 너무 많습니다. 잠시 후 다시 시도하세요.",
    REGISTER_REJECTED: "계정 등록을 시작하지 못했습니다.",
    INVALID_TOKEN: "인증 토큰이 유효하지 않거나 만료되었습니다.",
    INVALID_CREDENTIALS: "이메일 또는 비밀번호가 올바르지 않습니다.",
    INVALID_REFRESH_TOKEN: "리프레시 토큰이 유효하지 않습니다.",
    INTERNAL_SERVER_ERROR: "서버 오류가 발생했습니다.",
    UNKNOWN_ERROR: "알 수 없는 오류가 발생했습니다.",
    WIKI_PAGES_LIST_FAILED: "페이지를 불러오지 못했습니다.",
    WIKI_SEARCH_FAILED: "검색에 실패했습니다.",
    WIKI_PAGE_NOT_FOUND: "페이지를 찾을 수 없습니다.",
    WIKI_PAGE_FORBIDDEN: "이 페이지에 접근할 권한이 없습니다.",
    WIKI_PAGE_FETCH_FAILED: "페이지를 불러오지 못했습니다.",
    WIKI_PAGE_CREATE_FAILED: "페이지 생성에 실패했습니다.",
    WIKI_PAGE_PARENT_CYCLE: "상위 페이지 설정이 순환 구조를 만듭니다.",
    WIKI_PAGE_UPDATE_FAILED: "페이지 저장에 실패했습니다.",
    WIKI_PAGE_DELETE_FAILED: "페이지 삭제에 실패했습니다.",
    WIKI_BLOCK_CREATE_FAILED: "블록 생성에 실패했습니다.",
    WIKI_BLOCK_NOT_FOUND: "블록을 찾을 수 없습니다.",
    WIKI_BLOCK_UPDATE_FAILED: "블록 업데이트에 실패했습니다.",
    WIKI_BLOCK_DELETE_FAILED: "블록 삭제에 실패했습니다.",
    ADMIN_GROUPS_LIST_FAILED: "그룹 목록을 불러오지 못했습니다.",
    ADMIN_AGENTS_LIST_FAILED: "agent 목록을 불러오지 못했습니다.",
    ADMIN_AGENT_CREATE_FAILED: "agent 생성에 실패했습니다.",
    ADMIN_AGENT_NOT_FOUND: "agent를 찾을 수 없습니다.",
    ADMIN_AGENT_UPDATE_FAILED: "agent 업데이트에 실패했습니다.",
    ADMIN_GROUP_NAME_CONFLICT: "같은 이름의 그룹이 이미 존재합니다.",
    ADMIN_GROUP_CREATE_FAILED: "그룹 생성에 실패했습니다.",
    ADMIN_GROUP_NOT_FOUND: "그룹을 찾을 수 없습니다.",
    ADMIN_GROUP_FETCH_FAILED: "그룹을 불러오지 못했습니다.",
    ADMIN_GROUP_SYSTEM_MUTATION_FORBIDDEN: "시스템 그룹은 수정할 수 없습니다.",
    ADMIN_GROUP_UPDATE_FAILED: "그룹 업데이트에 실패했습니다.",
    ADMIN_GROUP_SYSTEM_DELETE_FORBIDDEN: "시스템 그룹은 삭제할 수 없습니다.",
    ADMIN_GROUP_DELETE_FAILED: "그룹 삭제에 실패했습니다.",
    ADMIN_GROUP_MEMBERS_LIST_FAILED: "그룹 멤버를 불러오지 못했습니다.",
    ADMIN_GROUP_MEMBERS_ADD_FAILED: "그룹 멤버 추가에 실패했습니다.",
    ADMIN_MEMBERSHIP_NOT_FOUND: "소속 정보를 찾을 수 없습니다.",
    ADMIN_MEMBERSHIP_DELETE_FAILED: "소속 정보 삭제에 실패했습니다.",
    ADMIN_USERS_LIST_FAILED: "사용자 목록을 불러오지 못했습니다.",
    ADMIN_USER_GROUPS_UPDATE_FAILED: "사용자 소속 업데이트에 실패했습니다.",
    ADMIN_PAGE_PERMISSIONS_FETCH_FAILED: "페이지 권한을 불러오지 못했습니다.",
    ADMIN_PAGE_PERMISSIONS_SET_FAILED: "페이지 권한 업데이트에 실패했습니다.",
    ADMIN_PAGE_PERMISSION_NOT_FOUND: "페이지 권한을 찾을 수 없습니다.",
    ADMIN_PAGE_PERMISSION_DELETE_FAILED: "페이지 권한 삭제에 실패했습니다.",
    ADMIN_PAGE_INHERITANCE_FETCH_FAILED: "페이지 상속 설정을 불러오지 못했습니다.",
    ADMIN_PAGE_INHERITANCE_SET_FAILED: "페이지 상속 설정 업데이트에 실패했습니다.",
    ADMIN_KPI_OVERVIEW_FAILED: "KPI를 불러오지 못했습니다.",
    MEETINGS_LIST_FAILED: "회의를 불러오지 못했습니다.",
    MEETING_NOT_FOUND: "회의를 찾을 수 없습니다.",
    MEETING_FORBIDDEN: "이 회의에 접근할 권한이 없습니다.",
    MEETING_FETCH_FAILED: "회의를 불러오지 못했습니다.",
    MEETING_CREATE_FAILED: "회의 생성에 실패했습니다.",
    MEETING_UPDATE_FAILED: "회의 업데이트에 실패했습니다.",
    MEETING_DELETE_FAILED: "회의 삭제에 실패했습니다.",
    MEETING_TRANSCRIPT_CREATE_FAILED: "전사 추가에 실패했습니다.",
    MEETING_SUMMARY_CREATE_FAILED: "요약 추가에 실패했습니다.",
    MEETING_PIPELINE_TRANSCRIPTS_MISSING: "이 회의에는 아직 전사 내용이 없습니다.",
    MEETING_PIPELINE_RUN_FAILED: "AI 파이프라인 실행에 실패했습니다.",
    MEETING_REALTIME_TRANSCRIPTS_FETCH_FAILED: "실시간 전사를 가져오지 못했습니다.",
    MEETING_REALTIME_TRANSCRIPT_UPSERT_FAILED: "실시간 전사 업데이트에 실패했습니다.",
    MEETING_AGENT_EVENTS_FETCH_FAILED: "agent 이벤트를 불러오지 못했습니다.",
    MEETING_AGENT_SESSIONS_FETCH_FAILED: "활성 agent 세션을 불러오지 못했습니다.",
    MEETING_AGENT_NOT_FOUND_OR_INACTIVE: "agent를 찾을 수 없거나 비활성 상태입니다.",
    MEETING_AGENT_INVOKE_FAILED: "agent 호출에 실패했습니다.",
    MEETING_AGENT_SESSION_NOT_FOUND: "활성 agent 세션을 찾을 수 없습니다.",
    MEETING_AGENT_LEAVE_FAILED: "agent 세션 종료에 실패했습니다.",
    MEETING_AGENT_RESPONSE_FAILED: "agent 응답 생성에 실패했습니다.",
  },
};

export function getApiErrorMessage(
  error: unknown,
  locale: SupportedLocale,
  fallbackMessage: string
) {
  if (error instanceof ApiError) {
    const code = error.code;
    if (code) {
      const localized =
        messagesByLocale[locale][code] ?? messagesByLocale[defaultLocale][code];
      if (localized) {
        return localized;
      }
    }

    return (error.detail ?? error.message) || fallbackMessage;
  }

  return error instanceof Error ? error.message : fallbackMessage;
}

export function useApiErrorMessage() {
  const locale = useLocale();
  return useCallback(
    (error: unknown, fallbackMessage: string) =>
      getApiErrorMessage(error, locale, fallbackMessage),
    [locale]
  );
}
